# 补充

- 不够

# 用户自定义异常

举例：


    class Networkerror(RuntimeError):
        def __init__(self, arg):
            self.args = arg


​    
    try:
        raise Networkerror("Bad hostname")
    except Networkerror as e:
        print(type(e.args))
        print(e.args)


输出：

```
<class 'tuple'>
('B', 'a', 'd', ' ', 'h', 'o', 's', 't', 'n', 'a', 'm', 'e')
```

不清楚的：

- <span style="color:red;">为什么会输出一个 tuple？而且，内容是这个？</span>












# 相关

1. [Python基础教程 w3cschool](https://www.w3cschool.cn/Python/)
2. [Python 3 教程 菜鸟教程](http://www.runoob.com/Python3/Python3-tutorial.html)
